### ISSUE TITLE
Remove gaps from grid layout

### ISSUE THREAD

**Issue by JesseRWeigel** [fus-marcom/bulletin-react#16]
Maybe try using the masonry react module that was used in the first version of the Resources page for the ci-react project. See this commit ( https://github.com/fus-marcom/ci-react/commit/3edd50549242397e0268cc1c862edff011b8c590#diff-eb5ff544cae584eda8b7362ae88cff46 )

![image](https://user-images.githubusercontent.com/11077930/31731122-05d257cc-b402-11e7-8350-064f35585470.png)

**Comment by pantharshit00** [comment]
I will get to it

**Comment by pantharshit00** [comment]
#47 closes this
