### ISSUE TITLE
Make FUS logo  and 'Current Bulletin' a link to the home screen.

### ISSUE THREAD

**Issue by JesseRWeigel** [fus-marcom/bulletin-react#17]
Be sure to use the React Router ```<Link>``` component.

**Comment by SebastianCApostolescu** [comment]
I believe I already made the FUS logo link to the homepage.

**Comment by SebastianCApostolescu** [comment]
Correction: 
I did it in PR #5 https://github.com/fus-marcom/bulletin-react/pull/5/commits/8e1ba1de9aebbb65367c59c52e3ec80b85374ffb
Guess it was removed.

**Comment by JesseRWeigel** [comment]
I think you are right, but somewhere along the line it was changed back. I
think it may have been in another PR that was merged but didn't have your
changes. I must not have noticed it at the time.

**Comment by JesseRWeigel** [comment]
#25
