### ISSUE TITLE
Add 'All' as an option under 'Categories' in side drawer

### ISSUE THREAD

**Issue by JesseRWeigel** [fus-marcom/bulletin-react#18]
This should display all posts starting with the newest first.

**Comment by DennyScott** [comment]
Hey I'd like to take this on. :) Do you want all to come before or after the other listed categories?

**Comment by JesseRWeigel** [comment]
Before please!

**Comment by JesseRWeigel** [comment]
It should look like this:

![image](https://user-images.githubusercontent.com/11077930/31735038-964791d0-b40e-11e7-9151-43594658ab47.png)

**Comment by JesseRWeigel** [comment]
#24
