### ISSUE TITLE
'Start' script issues

### ISSUE THREAD

**Issue by True14** [fus-marcom/bulletin-react#27]
The application uses a script called "start" which uses a module called "concurrently" to run two other scripts (start-back-dev and start-front) at the same time. When trying to run this script, I ran into some issues (the 'm' in npm being unrecognized, single quotes causing problems) and had to change the script in order for it to work. This may be platform specific so I would like to see if this happened to anyone else. 

Original Script:
` "start":"concurrently 'npm run start-front' 'npm run start-back-dev'"`
   
Fixed Script (for me):
`"start": "concurrently \"npm run start-front\" \"npm run start-back-dev\""`

Platform:
Windows 10
Node 8.7.0
npm 5.4.2

**Comment by JesseRWeigel** [comment]
#28
