### ISSUE TITLE
Truncate post content for Grid view only.

### ISSUE THREAD

**Issue by JesseRWeigel** [fus-marcom/bulletin-react#32]
Truncate at somewhere around 300 characters and add "...Continue reading" to the end of truncated text. Make "...Continue reading" a link to the post details page.

Example (but no need to include the post title after "...Continue reading"):

![image](https://user-images.githubusercontent.com/11077930/31779600-7eebbe90-b4c1-11e7-8cef-ce2eab3e49c9.png)

**Comment by pantharshit00** [comment]
I will get to it. What is the truncate limit?

**Comment by Rud156** [comment]
Just opened a PR. Could you have a look

**Comment by pantharshit00** [comment]
@Rud156 Please see my review in your PR. The hacky thing you have done is REALLY too hacky. Also dont use the static class while styling.

**Comment by Rud156** [comment]
@pantharshit00 I'll make you a collaborator. Could you change it and show. The problem this is occurring is that I can't use any react component with the html string so got stuck as to how to go about it. Your solution requires a react component. Putting anything outside `Typography` component places it on the next line.

**Comment by Rud156** [comment]
@pantharshit00 Sent you an invite. Could you check?

**Comment by Rud156** [comment]
Even this is not working
```html
<Typography
          type="body2"
          gutterBottom
        >
          <span dangerouslySetInnerHTML={{ __html: content }} />
          <span>
            Hello World
          </span>
        </Typography>
```
