### ISSUE TITLE
Add a print view

### ISSUE THREAD

**Issue by JesseRWeigel** [fus-marcom/bulletin-react#43]
When a user clicks on the printer icon they view should change to something that looks like this: 
![image](https://user-images.githubusercontent.com/11077930/31842437-1e2e9266-b5bc-11e7-987f-e4b48de216a1.png)

Please note: The side drawer is completely hidden in this view, even on desktop. The font changes to a serif font.

**Comment by pantharshit00** [comment]
I will get to it today
