### ISSUE TITLE
UI Glitch when opening the Logout menu

### ISSUE THREAD

**Issue by SebastianCApostolescu** [fus-marcom/bulletin-react#45]
When you open the Logout menu (3 dots icon), the view glitches.

- The "Bulletin" text from the AppBar shifts to the left.
- Some posts are not displayed.

See this Issue in video [HERE](https://youtu.be/RWp_HVGNk-0).

**Comment by pantharshit00** [comment]
I also encountered the glitch. But I found the fix. add this to the global stylesheet.
```css
body {
    overflow: auto !important;
}
```

It fixes it as the overflow styles added to body is overridden by this.

**Comment by SebastianCApostolescu** [comment]
Fixed in PR #46 .
